---
title: "Exploded code"
subtitle: "Using flipbookr and xaringan"
author: "Me"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:9
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---


```{r, include = F}
# This is the recommended set up for flipbooks
# you might think about setting cache to TRUE as you gain practice --- building flipbooks from scratch can be time consuming
knitr::opts_chunk$set(fig.width = 6, message = F, warning = FALSE, comment = "", cache = T)

options(tibble.print_min = 55)
options(knitr.duplicate.label = "allow")
options(width=300) # prevents data wrapping 
```


```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 40%}

@media print {
  .has-continuation {
    display: block;
  }
}

code.r.hljs.remark-code{
  position: relative;
  overflow-x: hidden;
}


code.r.hljs.remark-code:hover{
  overflow-x:visible;
  width: 500px;
  border-style: solid;
}
```


<!-- README.md is generated from README.Rmd. Please edit that file -->

---




```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  message = F,
  warning = F,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

---


`r flipbookr::chunk_reveal("ggstamp", left_assign = "detect")`


```{r ggstamp, include = FALSE}
library(tidyverse)
library(ggstamp)  
set.seed(1243)
tibble::tibble(x = rnorm(40000, sd = .7),
       y = rnorm(40000, sd = .7)) %>% 
  ggplot() + 
  aes(x = x, y = y) +
  geom_hex(show.legend = F, color = alpha("white", 0)) + 
  coord_equal() + 
  stamp_polygon_inverse(radius = 2, radius_outer = Inf
                        ) + 
  stamp_polygon(alpha = .2, n = 5, size = 1.75,
                fill = "magenta", color = "grey15",
                rotation = -.55) + 
  stamp_polygon(radius = .4, n = 3,
                x0 = .3, y0 = .77, rotation = -.4,
                alpha = 1, fill = "orange", size = 0) + 
  stamp_text(angle = 30, label = "ggstamp",
             x = .7, y = -1,
             color = "snow1") + 
  stamp_text(angle = 30, label = "github.com/EvaMaeRey/ggstamp",
             x = .7, y = -1.45, size = 1.8,
             color = "grey85") + 
  stamp_polygon(radius = 2, 
                alpha = 0, size = 3,
                color = "plum3") + 
  theme_void() +
  ggxmean::stamp_normal_dist(sd = .2, alpha = .8, height = 1.5) + 
  stamp_point(xy = pos_wrap(n = 22, ncol = 6, width = .15, x0 = -.95, y0 = -.3), size = 1,
              color = "seagreen2")
```



---


`r flipbookr::chunk_reveal("ggsample", left_assign = "detect", break_type = 20)`


```{r ggsample, include = FALSE}
magick::image_read("pngs/noun_hat_2167247.png") %>% 
  magick::image_flip() %>% 
  magick::image_write("pngs/my_hat.png")

library(ggstamp)  
tibble::tibble(x = rnorm(50000, sd = 1.2, mean = -.45),
       y = rnorm(50000, sd = 1.2, mean = -.75)) %>% 
  ggplot() + 
  aes(x = x, y = y) +
  stamp_polygon(radius = 2, size = 3.5,
                fill = "grey20"
                        ) +
  ggpointdensity::geom_pointdensity(show.legend = F,
                                    size = 5) +
  scale_color_viridis_c(option = "magma", begin = .4) + 
  coord_equal(xlim = c(-2,2), ylim = c(-2,2)) + 
  stamp_polygon_inverse(radius = 2, radius_outer = Inf
                        ) +
  stamp_polygon(radius = 2, size = 5.5,
                color = "grey20",
                        alpha = 0
                        ) +
  stamp_png2(png = "pngs/noun_Grabbing Hand_2312499.png",
             width = 2.5,
             x0 = .32,
             y0 = .25,
             color = "grey20"
             ) +
  stamp_png2(png = "pngs/my_hat.png",
             x0 = -.4, 
             y0 = -.6,
             width = 2.7, 
             color = "grey20") + 
  theme_void() +
  stamp_text(x = runif(6, min = -.75, max = -.05),
             y = runif(6, min = -1.15, max = -.45),
             angle = sample(1:6)*20,
             size = 10,
             alpha = 1,
             color = "grey20",
             label = sample("sample" %>% 
                              str_split("") %>% 
                              .[[1]] %>% 
                              rep(1))
             ) +
      stamp_text(x = rnorm(2, mean = 0, sd = .1),
             y = rnorm(2, mean = 0, sd = .1),
             angle = sample(1:2)*20,
             size = 12,
             alpha = 1,
             color = "grey20",
             label = sample("gg" %>% 
                              str_split("") %>% 
                              .[[1]] %>% 
                              rep(1))
             )
  
```

